#!/bin/bash


if [[ -z ${GEOSLURP_SETTINGS+x} ]];
then
    runuser -u ${GEOSLURP_USER} -- geoslurper.py --user ${POSTGRES_USER} --password ${POSTGRES_PASSWORD} $@
else
    runuser -u ${GEOSLURP_USER} -- geoslurper.py --user ${POSTGRES_USER} --password ${POSTGRES_PASSWORD} --local-settings ${GEOSLURP_SETTINGS} $@
fi
