#!/bin/bash

if [[ -z ${GEOSLURP_SETTINGS+x}]];
then
    geoslurper.py --user ${GEOSLURP_USER} --password ${GEOSLURP_UPASSWD} $@
else
    geoslurper.py --user ${GEOSLURP_USER} --password ${GEOSLURP_UPASSWD} --local-settings ${GEOSLURP_SETTINGS} $@
fi
