#!/bin/bash

if [[ -z ${GEOSLURP_SETTINGS+x} ]];
then
    runuser -u ${GEOSLURP_USER} -- geoslurper.py --user ${GEOSLURP_USER} --password ${GEOSLURP_UPASSWD} $@
else
    runuser -u ${GEOSLURP_USER} -- geoslurper.py --user ${GEOSLURP_USER} --password ${GEOSLURP_UPASSWD} --local-settings ${GEOSLURP_SETTINGS} $@
fi
