#!/bin/bash


if [[ -z ${GEOSLURP_SETTINGS+x}]];
then
    geoslurper.py --user ${POSTGRES_USER} --password ${POSTGRES_PASSWORD} $@
else
    geoslurper.py --user ${POSTGRES_USER} --password ${POSTGRES_PASSWORD} --local-settings ${GEOSLURP_SETTINGS} $@
fi
